workout_name = input("What workout are we doing today: ")
exercise = input("What exercise: ")
weight = float(input("How much weight: "))
reps = int(input("How many reps: "))
print("---Workout Entry---")
print(f"Workout: {workout_name}")
print(f"Exercise: {exercise}")
print(f"Weight: {weight}")
print(f"Reps: {reps}")