exercise = input("What's your favoriate exercise? ")
weight = int(input("How much weight (lbs) are we lifting? "))
reps = int(input(f"How many reps are we doing with {weight} lbs? "))
print(f"Exercise: {exercise.title()}")
print(f"Weight: {weight}")
print(f"Reps: {reps}")
print(f"Total volume of weight lifted is: {weight * reps} lbs")